version: 2
jobs:
  build:
    docker:
      - image: node:7.7.3
    working_directory: ~/react-nvd3
    steps:
      - checkout
      - run: npm install
      - run: ./node_modules/gulp/bin/gulp.js jest
