version: 2
jobs:
  build:
    docker:
      - image: node:7.7.3
    working_directory: ~/react-nvd3
    steps:
      - checkout
      - run: mkdir -p ~/react-nvd3/artifacts
      - run: npm install
      - run: ./node_modules/gulp/bin/gulp.js jest
      - store_artifacts:
          path: ~/react-nvd3/artifacts
